import {createRequire} from 'node:module';import {pathToFileURL} from 'node:url';import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.AERO_PLAYWRIGHT_MODULE||'playwright');
const packaged=process.env.AERO_CHROMIUM_MODULE?(await import(process.env.AERO_CHROMIUM_MODULE)).default:null;
const browser=await chromium.launch({headless:true,executablePath:process.env.AERO_CHROMIUM_EXECUTABLE||undefined,args:[...(packaged?.args||[]).filter(a=>a!=='--single-process'),'--allow-file-access-from-files','--enable-unsafe-swiftshader']});
const root=path.resolve('dist'),errors=[];
async function setup({legacy=false}={}){const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await context.addInitScript(({legacy})=>{Object.defineProperty(document,'modelContext',{value:{registerTool(tool){window.flightTool=tool}}});Object.defineProperty(navigator,'deviceMemory',{value:1});if(legacy){window.PointerEvent=undefined;HTMLDialogElement.prototype.showModal=undefined;HTMLDialogElement.prototype.close=undefined;const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type.includes('webgl')?null:get.call(this,type,...args)}}},{legacy});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));return{context,page};}
const server=http.createServer((req,res)=>{const prefix='/aero-explorer/';if(!req.url.startsWith(prefix)){res.writeHead(404).end();return}let relative=decodeURIComponent(new URL(req.url,'http://localhost').pathname.slice(prefix.length));if(relative.endsWith('/')||!relative)relative+='index.html';const file=path.resolve(root,relative);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404).end();return}const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.webp':'image/webp'};res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream'});res.end(fs.readFileSync(file))});
try{
 const {context,page}=await setup({legacy:true}),requests=[];page.on('request',r=>requests.push(r.url()));await page.goto(pathToFileURL(path.join(root,'standalone.html')).href);await page.waitForFunction(()=>window.flightTool&&document.getElementById('preflight').hidden);assert.equal((await page.evaluate(()=>window.flightTool.execute({}))).tier,'lite');await page.locator('#tutorialStart').click();await page.locator('#vehicle').selectOption('water');await page.waitForTimeout(250);assert.equal((await page.evaluate(()=>window.flightTool.execute({}))).vehicle,'water');assert.equal(requests.filter(u=>!u.startsWith('data:')&&u!==pathToFileURL(path.join(root,'standalone.html')).href).length,0,'Standalone loads no other file/network game asset');await context.close();
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url='http://127.0.0.1:'+server.address().port+'/aero-explorer/ja/';const hosted=await setup();const missing=[];hosted.page.on('response',r=>{if(r.status()>=400)missing.push(r.url())});await hosted.page.goto(url);await hosted.page.waitForFunction(()=>window.flightTool&&document.getElementById('preflight').hidden);assert.equal(await hosted.page.locator('html').getAttribute('lang'),'ja');await hosted.page.locator('#tutorialStart').click();await hosted.page.locator('#language').selectOption('en');assert(hosted.page.url().endsWith('/aero-explorer/en/'));assert.equal((await hosted.page.evaluate(()=>window.flightTool.execute({}))).locale,'en');assert.deepEqual(missing,[]);await hosted.context.close();assert.deepEqual(errors,[]);console.log('Delivery: isolated standalone, no WebGL/PointerEvent/native dialog fallback, and HTTP project-subpath assets/language navigation passed.');
}finally{server.close();await browser.close()}
