import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const root=path.resolve('dist'),json=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const manifest=json('assets/photos/manifest.json'),destinations=json('assets/destinations.json'),locales=Object.keys(json('assets/i18n.json'));
assert.equal(manifest.assets.length,26);assert.equal(destinations.length,11);assert.equal(manifest.assets.filter(a=>a.is360).length,2);
const ids=new Set();for(const a of manifest.assets){assert(!ids.has(a.id));ids.add(a.id);const image=fs.readFileSync(path.join(root,'assets/photos',a.file));assert.equal(image.subarray(0,4).toString(),'RIFF');assert.equal(image.subarray(8,12).toString(),'WEBP');assert.equal(image.length,a.bytes);assert.equal(crypto.createHash('sha256').update(image).digest('hex'),a.sha256);assert(a.author&&a.changes&&a.license&&a.licenseUrl.startsWith('https://')&&a.sourcePage.startsWith('https://'));assert.match(a.license,/CC|Public domain/);assert(a.factSources.every(url=>url.startsWith('https://')));if(a.is360){assert.equal(a.dimensions[0],a.dimensions[1]*2);assert(/360|equirect/i.test(a.projection))}}
for(const place of destinations){assert(Number.isFinite(place.lat)&&Math.abs(place.lat)<=85);assert(Number.isFinite(place.lon)&&Math.abs(place.lon)<=180);assert(ids.has(place.photoId));assert(place.photoIds.every(id=>ids.has(id)));assert(place.sourceUrls.length&&place.sourceUrls.every(url=>url.startsWith('https://')));for(const locale of locales){assert(place.name[locale]?.trim());assert(place.description[locale]?.trim())}}
const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),standalone=fs.readFileSync(path.join(root,'standalone.html'),'utf8');assert(!html.includes('id="googleKey"'));assert(!html.includes('id="weatherEndpoint"'));assert(html.includes('data-auto-locale="true"'));assert(!fs.readFileSync(path.join(root,'ja/index.html'),'utf8').includes('data-auto-locale="true"'));for(const a of manifest.assets){assert(standalone.includes('"'+a.id+'":"data:image/webp;base64,'),'singlefile embeds '+a.id)}assert(standalone.includes('photoCreditsDialog'),'singlefile licenses are readable without local side files');assert(!standalone.includes('href="assets/photos/PHOTO_CREDITS.html"'));
console.log('Explorer content: 26 licensed image hashes; 2 true 2:1 panoramas; 11 × 22 destinations; no player key fields; all photos and credits embedded in standalone passed.');

for(const p of json('assets/places.json').pois){assert(ids.has(p.photoId),p.id+' has a matching local photo');if(p.id==='kaohsiung-chang-gung')assert.equal(p.photoScenery,false)}
