import {createRequire} from 'node:module';import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.AERO_PLAYWRIGHT_MODULE||'playwright');
const project=process.env.AERO_SITE_ROOT||process.cwd(),root=process.env.AERO_GITHUB_OUTPUT||path.join(project,'.aero-output/AERO_Explorer'),output=process.env.AERO_QA_OUTPUT||path.join(project,'.qa-output');fs.mkdirSync(output,{recursive:true});
const photos=JSON.parse(fs.readFileSync(path.join(root,'assets/photos/manifest.json'),'utf8')).assets;
const packaged=process.env.AERO_CHROMIUM_MODULE?(await import(process.env.AERO_CHROMIUM_MODULE)).default:null;let browser;
const server=http.createServer((req,res)=>{let relative;try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(pathname==='/single/index.html')relative='standalone.html';else if(pathname.startsWith('/AERO_Explorer/'))relative=pathname.slice('/AERO_Explorer/'.length);else{res.writeHead(404).end();return}}catch{res.writeHead(400).end();return}if(!relative||relative.endsWith('/'))relative+='index.html';const file=path.resolve(root,relative);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404).end();return}const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webp':'image/webp','.svg':'image/svg+xml','.webmanifest':'application/manifest+json'};res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream'});res.end(fs.readFileSync(file))});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const local='http://127.0.0.1:'+server.address().port;
async function setup(){const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,locale:'ja-JP',serviceWorkers:'block'});await context.route('**/*',route=>route.request().url().startsWith(local+'/')||/^(data:|blob:)/.test(route.request().url())?route.continue():route.abort('internetdisconnected'));await context.addInitScript(()=>{Object.defineProperty(document,'modelContext',{value:{registerTool(tool){window.flightTool=tool}}});Object.defineProperty(navigator,'deviceMemory',{value:1});Object.defineProperty(navigator,'geolocation',{value:{getCurrentPosition(_success,error){setTimeout(()=>error({code:1,message:'Delivery QA denied'}),20)}}});});const page=await context.newPage(),missing=[],errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().startsWith(local+'/')&&r.status()>=400)missing.push({url:r.url(),status:r.status()})});return{context,page,missing,errors}}
async function ready(page){await page.waitForFunction(()=>window.flightTool&&document.getElementById('preflight')?.hidden);if(await page.locator('#tutorialStart').isVisible())await page.locator('#tutorialStart').click();assert.equal(await page.locator('#locationMap').evaluate(el=>el.tagName),'DIV');assert.equal(await page.locator('#locationMap iframe').count(),0);}
try{
 browser=await chromium.launch({headless:true,executablePath:process.env.AERO_CHROMIUM_EXECUTABLE,args:[...(packaged?.args||[]).filter(a=>a!=='--single-process'),'--enable-unsafe-swiftshader']});
 const hosted=await setup();await hosted.page.goto(local+'/AERO_Explorer/ja/');await ready(hosted.page);assert.equal(await hosted.page.locator('html').getAttribute('lang'),'ja');assert.equal(await hosted.page.locator('link[rel="canonical"]').getAttribute('href'),'https://kuonanhong.github.io/AERO_Explorer/ja/');await hosted.page.locator('#language').selectOption('en');assert.equal(new URL(hosted.page.url()).pathname,'/AERO_Explorer/en/');await hosted.page.reload();await ready(hosted.page);assert.equal(await hosted.page.locator('html').getAttribute('lang'),'en');assert.equal(await hosted.page.locator('link[rel="canonical"]').getAttribute('href'),'https://kuonanhong.github.io/AERO_Explorer/en/');assert.deepEqual(hosted.missing,[]);assert.deepEqual(hosted.errors,[]);await hosted.page.screenshot({path:path.join(output,'v41-github-en-mobile.png')});await hosted.context.close();
 const single=await setup();await single.page.goto(local+'/single/index.html');await ready(single.page);await single.page.locator('#language').selectOption('en');assert.equal(new URL(single.page.url()).pathname,'/single/index.html','Single-file language changes preserve the arbitrary hosted filename');await single.page.reload();await ready(single.page);assert.equal(new URL(single.page.url()).pathname,'/single/index.html');assert.equal(await single.page.locator('html').getAttribute('lang'),'en');const inline=await single.page.evaluate(async()=>Promise.all(Object.entries(globalThis.AERO_PHOTO_ASSETS||{}).map(async([id,url])=>{const image=new Image();image.src=url;await image.decode();return{id,width:image.naturalWidth,height:image.naturalHeight}})));assert.equal(inline.length,photos.length);assert(inline.every(image=>image.width>0&&image.height>0));await single.page.locator('#photoButton').click();await single.page.waitForFunction(()=>document.getElementById('photoDialog').open&&document.getElementById('photoPreviewImage').naturalWidth>0);assert(await single.page.locator('#photoPreviewImage').evaluate(image=>image.src.startsWith('data:image/png;base64,')));await single.page.screenshot({path:path.join(output,'v41-hosted-single-photo.png')});await single.page.locator('#closePhoto').click();assert.deepEqual(single.missing,[]);assert.deepEqual(single.errors,[]);await single.context.close();
 const result={github:{path:'/AERO_Explorer/ja/ → /AERO_Explorer/en/ → reload',canonical:'https://kuonanhong.github.io/AERO_Explorer/en/',defaultDOMMap:true,missing:hosted.missing,errors:hosted.errors},single:{path:'/single/index.html',languageChangePreservedURL:true,reloadNo404:true,locale:'en',inlinePhotos:inline.length,defaultDOMMap:true,photoPreviewPNG:true,missing:single.missing,errors:single.errors},externalNetwork:'Blocked intentionally; no provider-render guarantee'};fs.writeFileSync(path.join(output,'github-target-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}finally{await browser?.close();await new Promise(resolve=>server.close(resolve));}
